-- funnel_ventas (Ciplastic) — schema Neon (migrado desde Supabase 2026-06-24)
-- Sin RLS (conectamos como owner). Identity BY DEFAULT (la app nunca pasa id).

CREATE TABLE opportunities (
  id text PRIMARY KEY,
  pipeline_stage_id text NOT NULL,
  contact_id text,
  contact_name text,
  contact_email text,
  contact_phone text,
  contact_tags text[] DEFAULT '{}'::text[],
  created_at timestamptz NOT NULL,
  updated_at timestamptz,
  monetary_value numeric DEFAULT 0,
  source text,
  status text DEFAULT 'open'::text,
  raw_json jsonb,
  synced_at timestamptz DEFAULT now()
);
CREATE INDEX idx_opp_created ON opportunities USING btree (created_at);
CREATE INDEX idx_opp_stage ON opportunities USING btree (pipeline_stage_id);

CREATE TABLE metrics_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date date NOT NULL,
  end_date date NOT NULL,
  sync_type text NOT NULL DEFAULT 'auto'::text,
  funnel jsonb NOT NULL,
  stages jsonb NOT NULL,
  times jsonb NOT NULL,
  sources jsonb NOT NULL,
  trend jsonb NOT NULL,
  opportunity_count integer,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX idx_snap_range ON metrics_snapshots USING btree (start_date, end_date, created_at DESC);

CREATE TABLE sync_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_type text NOT NULL,
  status text NOT NULL,
  opportunities_total integer,
  opportunities_new integer,
  opportunities_updated integer,
  error_message text,
  duration_ms integer,
  created_at timestamptz DEFAULT now()
);
